version: '3.8'

services:
  api:
    image: jorgedeveloper01/api-nest-delliv
    ports:
      - 3001:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/mydb

  front:
    image: jorgedeveloper01/front-next-delliv
    ports:
      - 3000:3000

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dellivDb
