version: '3.8'

services:
  api:
    image: rovanilla/nestjs-app
    container_name: api
    ports:
      - 3001:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/mydb

  front:
    image: sunny0183/nextjs-docker
    container_name: front
    ports:
      - 3000:3000

  database:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
