import type { Metadata } from "next";
import { Exo } from "next/font/google";
import { ToastContainer } from "react-toastify";
import Providers from "./provider";

const exo = Exo({
  subsets: ["latin"],
  display: "swap",
  variable: "--exo",
  weight: ["100", "400", "500"],
});
export const metadata: Metadata = {
  title: "Raven delivery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <Providers>
        <body className={exo.className}>
          <ToastContainer
            position="top-center"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
          {children}
        </body>
      </Providers>
    </html>
  );
}
