import type { Metadata } from "next";
import { Exo } from "next/font/google";
import Providers from "./provider";

const exo = Exo({
  subsets: ["latin"],
  display: "swap",
  variable: "--exo",
  weight: ["100", "400", "500"],
});
export const metadata: Metadata = {
  title: "Raven delivery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <Providers>
        <body className={exo.className}>{children}</body>
      </Providers>
    </html>
  );
}
